" >_ Customizations for the vim editor. Read more at https://github.com/dawsbot/vimrc-builder

set number " Show absolute line numbers on the left.
filetype plugin on " Auto-detect un-labeled filetypes
syntax on " Turn syntax highlighting on
set ai " Sets auto-indentation
set si " Sets smart-indentation
set noswapfile " Prevent vim from creating .swp files
set cursorline " Highlight current cursor line
set cursorcolumn " Highlight current cursor column
set tabstop=4 " Tab equal 4 spaces (default 4)
set shiftwidth=4 " Arrow function (>>) creates 4 spaces
set expandtab " Use spaces instead of a tab charater on TAB
set wrap " Wrap overflowing lines
set hlsearch " When searching (/), highlights matches as you go
set ignorecase " When searching (/), ignore case entirely
set smartcase " When searching (/), automatically switch to a case-sensitive search if you use any capital letters
set showmatch " Show matching brackets when text indicator is over them
set noerrorbells " Silence the error bell
set novisualbell " Visually hide the error bell
set foldcolumn=2 " Place a width 2 margin on the left
set encoding=utf8 " Set text encoding as utf8
set numberwidth=4 " Sets width of the 'gutter' column used for numbering to 4 (default 4)
