#!/bin/bash
#
# Fetch commit data

commit_message_file=$1

branch=$(git symbolic-ref -q HEAD)
type=$(echo ${branch} | sed -E 's/^refs\/heads\/(.*)XBE-[0-9]+.*$/\1/g')
issue=$(echo ${branch} | sed -E 's/^refs\/heads\/.*(XBE-[0-9]+).*$/\1/g')

if [[ "${type}" == "chore"*  ]]; then
    type="chore"
elif [[ "${type}" == "docs"*  ]]; then
    type="docs"
elif [[ "${type}" == "feat"*  ]]; then
    type="feat"
elif [[ "${type}" == "fix"*  ]]; then
    type="fix"
elif [[ "${type}" == "refactor"*  ]]; then
    type="refactor"
elif [[ "${type}" == "style"*  ]]; then
    type="style"
elif [[ "${type}" == "test"*  ]]; then
    type="test"
else
    type=""
fi

if [[ "${issue}" != "XBE"* ]]; then
    issue=""
fi

prefix="${type}(${issue}): "
if [[ -z "${type}" ]] || [[ -z "${issue}" ]]; then
    prefix=""
fi

printf "${prefix}"
