#!/bin/bash
#
# List all branches in a detailed way

git for-each-ref \
    --sort=-committerdate refs/heads/ \
    --sort=-committerdate \
    --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'

